version: "3"

volumes:
  node_modules_volume:

services:
  app:
    container_name: express-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # ポートフォワーディング
      - 3004:3000 # localのポート:コンテナのポート
    volumes:
      - .:/workspace:cached
      - node_modules_volume:/workspace/node_modules
    working_dir: /workspace
    tty: true
