version: '3'

volumes:
  node_modules:
  postgres:

services:
  app:
    image: node:16.13.2
    ports:
      - 3000:3000
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    command: sleep infinity
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: dms_coding_test 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
